from .hnd_common import register_common_handlers
from .hnd_example_markup import register_example_messages_handlers
from .hnd_example_buttons import register_example_kbd_buttons
from .hnd_privat_chat import privat_chat_router
from .hnd_events_in_group import events_in_group_router
from .hnd_changes_in_group_chat import changes_in_group_router
